### ISSUE TITLE
Latest release doesn't fix deprecation warnings

### ISSUE THREAD

**Issue by vonbraunbates** [moj-analytical-services/actions#8]
I am using commit `64fc048408ad8e05e3e3ab2bde08d87bd036ec46` which is currently marked as the latest release and tageed `v1`.  While the action does run to completion, it has the following deprecation warniings (and a couple of security ones) which I had hoped that this release would fix.  Should I ues a different release?

<h2 class="text-bold h4">Annotations</h2>
<h3>4 warnings</h3>
<p><a class="d-block no-underline Link--secondary color-fg-default" href="https://github.com/moj-analytical-services/p1-offloc-export/actions/runs/11370683679/job/31631025726">
<strong>Build, tag, and push image to Amazon ECR</strong>
</a></p>

<p>Your docker password is not masked. See https://github.com/aws-actions/amazon-ecr-login#docker-credentials for more information.</p>

<p>Your docker password is not masked. See https://github.com/aws-actions/amazon-ecr-login#docker-credentials for more information.</p>

<p>The following actions uses node12 which is deprecated and will be forced to run on node16: actions/checkout@v2, actions/setup-python@v2. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/</p>

<p>The following actions use a deprecated Node.js version and will be forced to run on node20: actions/checkout@v2, aws-actions/configure-aws-credentials@v2, aws-actions/amazon-ecr-login@v1, actions/setup-python@v2. For more info: <a href="https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/" class="link-gray" rel="noreferrer noopener nofollow" data-test-selector="linkified">https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/</a></p>

<h2 class="text-bold h4">Workflow file</h2>

```yaml
name: Build, tag, push, and make available image to pods
on:
  release:
    types: [published]
    tags:
      - "v*.*.*"
permissions:
  id-token: write
  contents: read
jobs:
  build-tag-push:
    name: Build, tag, and push image to Amazon ECR
    runs-on: ubuntu-20.04
    steps:
      - name: Build, tag, and push image to Amazon ECR
        uses: moj-analytical-services/actions-build-and-push-to-ecr@64fc048408ad8e05e3e3ab2bde08d87bd036ec46
        with:
          role-to-assume: REDACTED
        env:
          username: ${{ secrets.DOCKERHUB_DE_USERNAME }}
          pat: ${{ secrets.DOCKERHUB_READ_ONLY_PAT }}
      - name: Add cross-account permissions to an image on ECR
        uses: moj-analytical-services/actions-cross-account-ecr@v1
        with:
          role-to-assume: REDACTED
```
